/*
* When using this file, change `safe_explorer` to the database name that you have created on your system.
* Data will be imported after table creation
*/

CREATE TABLE `safe_explorer`.`organization_hierarchy` (
  `employee_id` VARCHAR(10) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `manager_id` VARCHAR(45) NULL,
  `email_address` VARCHAR(80) NULL,
  `cost_center` VARCHAR(10) NULL,
  `status` VARCHAR(10) NULL,
  `primary_team` VARCHAR(10) NULL,
  PRIMARY KEY (`employee_id`));

 
 /* Import data below */
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1000, 'Mason', 'York', 'Ghaziabad', 'Tajikistan', '', 'Nunc.lectus.pede@a.org', 6, 17);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1001, 'Abdul', 'Shepherd', 'Ribnitz-Damgarten', 'Ukraine', '', 'molestie.sodales@arcuiaculisenim.co.uk', 1, 92);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1002, 'May', 'Benton', 'Newtown', 'Sweden', '', 'massa@Suspendissenon.com', 9, 55);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1003, 'Katelyn', 'Koch', 'Jonesboro', 'Congo (Brazzaville)', '', 'id@vulputatelacus.com', 4, 47);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1004, 'Zorita', 'Hill', 'Pangnirtung', 'Cocos (Keeling) Islands', '', 'dis.parturient@uteros.net', 5, 87);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1005, 'Tasha', 'Floyd', 'Diano Arentino', 'Ghana', '', 'egestas@ascelerisque.ca', 8, 39);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1006, 'Basia', 'Stone', 'Hampstead', 'Cambodia', 1005, 'per@montes.edu', 9, 10);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1007, 'Dieter', 'Mayer', 'Bunbury', 'Holy See (Vatican City State)', 1005, 'rhoncus.Nullam@semperNamtempor.edu', 6, 24);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1008, 'Kristen', 'Pugh', 'Agra', 'Sudan', 1006, 'tincidunt.nibh.Phasellus@magnamalesuada.co.uk', 8, 57);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1009, 'Angelica', 'Wyatt', 'Imphal', 'Costa Rica', 1006, 'aliquam.eros.turpis@vitaeposuere.org', 10, 38);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1010, 'Jelani', 'Kinney', 'Rudiano', 'Hungary', 1007, 'nec@magna.net', 3, 70);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1011, 'Vernon', 'Rose', 'Poznań', 'Nauru', 1007, 'amet.ante.Vivamus@vitae.org', 9, 19);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1012, 'Wynne', 'Maddox', 'Satna', 'Libya', 1008, 'ut.pharetra.sed@dignissimMaecenasornare.net', 9, 52);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1013, 'Charlotte', 'Beasley', 'Zwickau', 'Mongolia', 1008, 'nonummy@adipiscing.ca', 8, 60);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1014, 'Lenore', 'Hunt', 'Aisemont', 'Netherlands', 1009, 'Etiam.bibendum@CuraeDonectincidunt.com', 3, 11);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1015, 'Rhoda', 'Byrd', 'Habergy', 'Lithuania', 1009, 'Nam.tempor@duinecurna.co.uk', 1, 28);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1016, 'Kuame', 'Koch', 'Ruisbroek', 'Denmark', 1010, 'Sed.dictum@vitaedolorDonec.net', 7, 48);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1017, 'Perry', 'Snider', 'Lourdes', 'Turkmenistan', 1010, 'gravida.molestie@vulputatevelit.co.uk', 4, 2);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1018, 'Jenette', 'Carr', 'Houtave', 'Kenya', 1010, 'Phasellus.elit@sed.ca', 8, 89);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1019, 'Kuame', 'Glass', 'Acquasanta Terme', 'Czech Republic', 1015, 'mus.Proin@maurisIntegersem.co.uk', 5, 73);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1020, 'Cheyenne', 'Farmer', 'Alassio', 'Uruguay', 1012, 'mollis.Integer.tincidunt@blanditcongueIn.co.uk', 4, 89);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1021, 'Quamar', 'Mcmillan', 'Baddeck', 'India', 1012, 'dolor@tortor.co.uk', 6, 22);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1022, 'Kirsten', 'Doyle', 'Kisi', 'Ireland', 1011, 'sem.ut@sedpede.co.uk', 6, 46);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1023, 'Zephr', 'Woodward', 'Estación Central', 'Curaçao', 1015, 'interdum.enim.non@inconsectetuer.ca', 4, 74);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1024, 'Keegan', 'Potts', 'Heist-aan-Zee', 'Colombia', 1010, 'Integer.vitae@ultricies.co.uk', 1, 85);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1025, 'Skyler', 'Shelton', 'Bon Accord', 'Bhutan', 1007, 'nunc@in.net', 9, 34);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1026, 'Wesley', 'Caldwell', 'Bionaz', 'South Georgia and The South Sandwich Islands', 1007, 'mauris@tinciduntdui.ca', 2, 16);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1027, 'Isaiah', 'Lee', 'Coinco', 'Saint Barthélemy', 1014, 'vitae.purus.gravida@non.ca', 1, 66);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1028, 'Hadley', 'Pearson', 'Coalhurst', 'Algeria', 1014, 'a.felis.ullamcorper@aliquam.edu', 7, 8);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1029, 'Hermione', 'Saunders', 'Midway', 'Viet Nam', 1015, 'vehicula.Pellentesque.tincidunt@condimentumegetvolutpat.ca', 6, 4);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1030, 'Naida', 'Russell', 'Salerno', 'Côte D''Ivoire (Ivory Coast)', 1008, 'ornare@elit.com', 3, 92);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1031, 'Ina', 'Mercer', 'Nicoya', 'Mayotte', 1007, 'luctus.sit@pretiumneque.net', 3, 97);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1032, 'Ivan', 'Coleman', 'Erciş', 'Sao Tome and Principe', 1009, 'aliquet@Phasellus.co.uk', 2, 7);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1033, 'Odessa', 'Burton', 'Grande Cache', 'Dominican Republic', 1014, 'eu@duiCras.com', 3, 59);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1034, 'Walter', 'Castro', 'Giove', 'Paraguay', 1015, 'aliquet.Phasellus.fermentum@amifringilla.com', 7, 26);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1035, 'Lareina', 'Talley', 'Tiruchirapalli', 'Haiti', 1010, 'Mauris@interdumliberodui.edu', 4, 26);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1036, 'Kay', 'Nolan', 'Tain', 'Pitcairn Islands', 1013, 'amet@aliquetodioEtiam.net', 4, 8);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1037, 'Octavia', 'Ballard', 'Edmonton', 'Ireland', 1008, 'eu.eros.Nam@semsemper.org', 5, 19);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1038, 'Mariam', 'Burton', 'Koningshooikt', 'Canada', 1014, 'mattis.semper.dui@ut.co.uk', 1, 31);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1039, 'Petra', 'Maddox', 'Dollard-des-Ormeaux', 'Jamaica', 1014, 'primis.in@quisaccumsan.com', 10, 60);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1040, 'Chastity', 'Cortez', 'Kamalia', 'South Africa', 1008, 'aliquam.enim.nec@iaculis.net', 8, 24);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1041, 'Samuel', 'Wooten', 'Belvedere Ostrense', 'Saudi Arabia', 1014, 'facilisis.facilisis@idante.edu', 8, 50);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1042, 'Kerry', 'Pittman', 'Ellesmere Port', 'Algeria', 1014, 'iaculis@sedorcilobortis.net', 10, 15);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1043, 'Daria', 'Gay', 'Ligny', 'Italy', 1015, 'consequat.lectus@eutelluseu.edu', 10, 77);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1044, 'Allegra', 'Wilder', 'Geest-GŽrompont-Petit-RosiŽre', 'Bonaire, Sint Eustatius and Saba', 1008, 'pellentesque.eget@disparturient.edu', 10, 16);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1045, 'Rahim', 'Graves', 'Meerut Cantonment', 'Cyprus', 1007, 'libero.at.auctor@velpede.co.uk', 1, 62);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1046, 'Louis', 'Levine', 'Llandovery', 'Venezuela', 1013, 'Donec.tempus.lorem@acturpisegestas.org', 1, 5);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1047, 'Hop', 'Vincent', 'Bolinne', 'Uganda', 1016, 'in.faucibus@Donecfringilla.org', 10, 22);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1048, 'Jaden', 'Noble', 'Malahide', 'Virgin Islands, United States', 1011, 'aliquet@nislMaecenasmalesuada.com', 5, 57);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1049, 'Teagan', 'Silva', 'Warszawa', 'Zimbabwe', 1015, 'in.magna@augue.com', 5, 74);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1050, 'Noel', 'Yang', 'Tuktoyaktuk', 'Bosnia and Herzegovina', 1014, 'sed.dui.Fusce@CurabiturmassaVestibulum.edu', 4, 69);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1051, 'Buffy', 'Sweet', 'Mira Bhayandar', 'Chad', 1007, 'Proin@amet.net', 9, 9);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1052, 'Cleo', 'Thompson', 'Pichidegua', 'Maldives', 1007, 'aliquam.eros.turpis@commodo.co.uk', 10, 93);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1053, 'Jakeem', 'Brown', 'Salt Spring Island', 'Puerto Rico', 1009, 'nisi.a@Morbiaccumsanlaoreet.ca', 7, 63);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1054, 'Nash', 'Gilbert', 'Calder', 'Morocco', 1010, 'dapibus.gravida@Phasellus.net', 1, 23);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1055, 'Jerry', 'Rojas', 'Ciplet', 'Kazakhstan', 1009, 'imperdiet.erat.nonummy@Etiamvestibulum.net', 7, 78);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1056, 'Desirae', 'Rasmussen', 'Ruddervoorde', 'Bhutan', 1011, 'et@sitametmassa.ca', 9, 14);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1057, 'Ingrid', 'Marsh', 'Ránquil', 'Thailand', 1010, 'auctor.ullamcorper@Lorem.edu', 5, 25);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1058, 'Leila', 'Jordan', 'Manfredonia', 'Ukraine', 1011, 'consequat.lectus.sit@Morbi.co.uk', 10, 40);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1059, 'Mariko', 'Campos', 'Salcito', 'Saint Kitts and Nevis', 1014, 'facilisis.eget@lobortisquispede.org', 3, 90);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1060, 'Hilda', 'Carpenter', 'Belmonte del Sannio', 'Cape Verde', 1006, 'ante.dictum.cursus@accumsan.com', 5, 79);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1061, 'Suki', 'Neal', 'Cropalati', 'Georgia', 1010, 'dolor.dolor.tempus@mauriselit.com', 9, 36);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1062, 'Imogene', 'Lopez', 'Caruaru', 'French Polynesia', 1006, 'feugiat.metus@Crasvulputatevelit.co.uk', 4, 93);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1063, 'Rajah', 'Hogan', 'Cochrane', 'Barbados', 1014, 'nec.tempus.scelerisque@eratEtiam.edu', 9, 30);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1064, 'Zoe', 'Robbins', 'Brecon', 'Costa Rica', 1011, 'tempus@Aliquamnecenim.net', 7, 41);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1065, 'Noelani', 'Serrano', 'Sarreguemines', 'Norfolk Island', 1012, 'vestibulum.lorem.sit@eratvel.edu', 3, 12);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1066, 'Beau', 'Lindsay', 'Champdani', 'Finland', 1008, 'eleifend.egestas.Sed@turpisnonenim.org', 5, 71);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1067, 'Simone', 'Cooke', 'Rae-Edzo', 'San Marino', 1009, 'pede.sagittis@diam.edu', 5, 41);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1068, 'Petra', 'Valdez', 'Neeroeteren', 'Romania', 1007, 'mauris.Suspendisse@antebibendumullamcorper.net', 4, 23);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1069, 'Neville', 'Daugherty', 'Tourinne', 'Estonia', 1008, 'sodales.elit@turpis.org', 1, 22);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1070, 'Lisandra', 'Myers', 'San Pedro', 'Syria', 1007, 'ac@arcu.net', 9, 45);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1071, 'Price', 'Murphy', 'Vernole', 'Jamaica', 1015, 'hendrerit.consectetuer.cursus@Nuncpulvinararcu.edu', 6, 1);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1072, 'Christen', 'Alvarado', 'Matagami', 'Indonesia', 1012, 'Vivamus.molestie.dapibus@auctorMauris.net', 4, 84);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1073, 'Allistair', 'Benjamin', 'Albagiara', 'Cambodia', 1013, 'magna.Cras.convallis@aduiCras.com', 2, 56);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1074, 'Sonia', 'Kent', 'Garaguso', 'Antarctica', 1010, 'at.velit.Pellentesque@velpede.ca', 6, 77);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1075, 'Florence', 'Daugherty', 'Stoke-on-Trent', 'Comoros', 1010, 'mauris.id@libero.ca', 5, 81);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1076, 'Rana', 'Vasquez', 'Río Claro', 'Saint Kitts and Nevis', 1010, 'leo.Morbi@nonummyutmolestie.com', 3, 75);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1077, 'Kimberley', 'Pope', 'Aylesbury', 'Dominican Republic', 1010, 'semper.dui.lectus@ipsumCurabitur.org', 7, 26);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1078, 'Emma', 'Byrd', 'Andernach', 'Burundi', 1015, 'dictum@gravida.ca', 10, 47);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1079, 'Theodore', 'Stewart', 'Latinne', 'Korea, South', 1012, 'auctor.quis.tristique@Seddiamlorem.ca', 8, 66);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1080, 'Stuart', 'Carrillo', 'Staßfurt', 'Belarus', 1013, 'semper@Sed.co.uk', 6, 11);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1081, 'Demetrius', 'Madden', 'Cádiz', 'Germany', 1016, 'nibh@urnanec.net', 7, 22);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1082, 'Xanthus', 'Whitaker', 'l''Escaillre', 'Cook Islands', 1010, 'felis.orci@antedictum.net', 7, 94);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1083, 'Dahlia', 'Jarvis', 'Bovigny', 'Denmark', 1009, 'risus@magnis.edu', 9, 90);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1084, 'Cara', 'Farrell', 'Molina', 'Trinidad and Tobago', 1006, 'dui.Cras@nonquamPellentesque.edu', 1, 24);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1085, 'Miriam', 'Lester', 'Cañas', 'Timor-Leste', 1012, 'ut.aliquam.iaculis@consequatpurusMaecenas.net', 10, 38);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1086, 'Ima', 'Russell', 'Beauport', 'Malaysia', 1010, 'aliquam.eros@vitaenibh.com', 9, 50);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1087, 'Adrienne', 'Walter', 'Corral', 'Curaçao', 1014, 'posuere.at.velit@Quisque.net', 8, 87);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1088, 'Maile', 'Whitley', 'Long Eaton', 'Botswana', 1008, 'egestas.a@dolor.com', 6, 56);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1089, 'Kim', 'Mccormick', 'Belvedere Ostrense', 'Poland', 1008, 'orci.sem@elementumategestas.com', 10, 25);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1090, 'Lilah', 'Roth', 'Livorno', 'Guinea-Bissau', 1008, 'lorem@ligula.ca', 5, 73);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1091, 'Aidan', 'Payne', 'San Felipe', 'Kyrgyzstan', 1013, 'in@risusDonecegestas.co.uk', 2, 20);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1092, 'Elvis', 'Grant', 'Wimmertingen', 'Argentina', 1008, 'at.lacus@Etiam.co.uk', 10, 31);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1093, 'Samson', 'Mayo', 'Shimoga', 'Central African Republic', 1013, 'habitant.morbi.tristique@liberolacus.org', 10, 82);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1094, 'Sonia', 'Morris', 'Bo‘lhe', 'Belarus', 1009, 'Nulla.dignissim.Maecenas@lobortisrisus.co.uk', 1, 99);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1095, 'Faith', 'Wilson', 'Tavistock', 'Germany', 1016, 'consequat.enim@nibhQuisque.com', 9, 31);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1096, 'Cameran', 'Frye', 'Flint', 'South Sudan', 1013, 'Vestibulum@Donecfelis.co.uk', 5, 95);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1097, 'Zenaida', 'Good', 'Bonn', 'Belarus', 1009, 'et.tristique@nulla.ca', 5, 90);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1098, 'Lucas', 'Gamble', 'Brusson', 'Guinea-Bissau', 1016, 'pede.Nunc@blanditcongue.org', 10, 22);
INSERT INTO organization_hierarchy (employee_id, first_name, last_name, city, country, manager_id, email_address, status, primary_team) VALUES (1099, 'Miranda', 'Baird', 'Belsele', 'Brazil', 1012, 'lacus.Etiam.bibendum@tincidunttempusrisus.edu', 2, 54);
